import { fail, mapFail, ok, type StructuredResult } from "./result.js";
import type { GateUseClaimV1, KernelState, TerminalOutcomeV1, WinningAttemptPhase } from "./types.js";
import { CONTRACT, TERMINAL_STATES } from "./types.js";
import { rejectObservationIdReuse } from "./identity.js";
import { appendRecord } from "./state.js";
import { observationHasTerminalState, terminalsForObservation } from "./derived-state.js";

const NON_TERMINAL_WINNER: readonly WinningAttemptPhase[] = [
  "CLAIMED",
  "ACTIVE",
  "IN_FLIGHT",
  "NON_TERMINAL",
  "TERMINAL_OUTCOME_UNKNOWN"
];

function claimsForObservation(state: KernelState, sourceObservationId: string): readonly GateUseClaimV1[] {
  return state.records.filter(
    (record): record is GateUseClaimV1 =>
      record.contractType === CONTRACT.GateUseClaim && record.sourceObservationId === sourceObservationId
  );
}

function allClaims(state: KernelState): readonly GateUseClaimV1[] {
  return state.records.filter((record): record is GateUseClaimV1 => record.contractType === CONTRACT.GateUseClaim);
}

function isTerminal(state: GateUseClaimV1["claimState"]): boolean {
  return (TERMINAL_STATES as readonly string[]).includes(state);
}

function isActiveAttempt(claim: GateUseClaimV1): boolean {
  if (claim.claimResult === "CLAIM_REJECTED") {
    return false;
  }
  return claim.claimState === "CLAIMED" || claim.claimState === "AVAILABLE";
}

export function attemptGateUseClaim(input: {
  state: KernelState;
  claim: GateUseClaimV1;
  winningAttemptPhase?: WinningAttemptPhase;
}): StructuredResult<{
  mutationPerformed: false;
  mutationAttempts: 0;
  record?: GateUseClaimV1;
  state?: KernelState;
}> {
  const reuse = rejectObservationIdReuse(input.state, input.claim.observationId);
  if (reuse.status !== "PASS") {
    return mapFail(reuse);
  }

  if (input.claim.attemptGeneration.length === 0) {
    return fail("FAILED", {
      field: "attemptGeneration",
      classification: "MISSING_ATTEMPT_GENERATION",
      message: "attemptGeneration MUST be explicit and MUST NOT be generated by the kernel"
    });
  }

  const existingClaims = claimsForObservation(input.state, input.claim.sourceObservationId);
  const successfulClaims = existingClaims.filter(
    (claim) => claim.claimState === "CLAIMED" && claim.claimResult === "CLAIMED"
  );
  if (successfulClaims.length >= 1) {
    return rejectCompetingClaim(input.state, input.claim);
  }

  if (observationHasTerminalState(input.state, input.claim.sourceObservationId)) {
    const terminals = terminalsForObservation(input.state, input.claim.sourceObservationId);
    if (terminals.some((terminal) => terminal.claimState === "TERMINAL_CONSUMED_SUCCESS")) {
      return fail("HOLD", {
        classification: "MUTATION_ATTEMPTS_EXCEEDED",
        message: "mutation attempts per observation <= 1"
      });
    }
    return fail("HOLD", {
      classification: "TERMINAL_NEVER_AVAILABLE",
      message: "terminal state → never AVAILABLE again"
    });
  }

  const activeSameGeneration = allClaims(input.state).filter(
    (claim) =>
      claim.logicalMutationId === input.claim.logicalMutationId &&
      claim.attemptGeneration === input.claim.attemptGeneration &&
      isActiveAttempt(claim)
  );
  if (activeSameGeneration.length >= 1) {
    return rejectCompetingClaim(input.state, input.claim);
  }

  const phase = input.winningAttemptPhase ?? input.claim.winningAttemptPhase;
  if (phase !== undefined && (NON_TERMINAL_WINNER as readonly string[]).includes(phase)) {
    return rejectCompetingClaim(input.state, input.claim);
  }

  const claimed: GateUseClaimV1 = {
    ...input.claim,
    claimState: "CLAIMED",
    claimResult: "CLAIMED"
  };
  return ok({
    record: claimed,
    state: appendRecord(input.state, claimed),
    mutationPerformed: false,
    mutationAttempts: 0
  });
}

function rejectCompetingClaim(
  state: KernelState,
  claim: GateUseClaimV1
): StructuredResult<{
  mutationPerformed: false;
  mutationAttempts: 0;
  record?: GateUseClaimV1;
  state?: KernelState;
}> {
  const rejected: GateUseClaimV1 = {
    ...claim,
    claimResult: "CLAIM_REJECTED",
    claimState: "AVAILABLE"
  };
  return fail("HOLD", {
    classification: "CLAIM_REJECTED",
    code: "CLAIM_REJECTED",
    message: "CLAIM_REJECTED → mutationPerformed=false → mutation attempts=0 → WAIT / HOLD",
    retryability: "WAIT",
    value: {
      mutationPerformed: false,
      mutationAttempts: 0,
      record: rejected,
      state: appendRecord(state, rejected)
    }
  });
}

export function recordTerminalOutcome(input: {
  state: KernelState;
  outcome: TerminalOutcomeV1;
  ambiguous?: boolean;
}): StructuredResult<{ record: TerminalOutcomeV1; state: KernelState }> {
  const reuse = rejectObservationIdReuse(input.state, input.outcome.observationId);
  if (reuse.status !== "PASS") {
    return mapFail(reuse);
  }

  if (input.outcome.claimId.length === 0) {
    return fail("FAILED", {
      field: "claimId",
      classification: "MISSING_FIELD",
      message: "TerminalOutcome@v1 MUST retain the reverse claimId reference"
    });
  }

  if (input.ambiguous === true) {
    const unknown: TerminalOutcomeV1 = {
      ...input.outcome,
      claimState: "TERMINAL_OUTCOME_UNKNOWN",
      mutationPerformed: "UNKNOWN"
    };
    return fail("HOLD", {
      classification: "TERMINAL_OUTCOME_UNKNOWN",
      message: "ambiguous outcome → TERMINAL_OUTCOME_UNKNOWN, mutationPerformed=UNKNOWN, HOLD; reconciliation required; no blind retry",
      value: { record: unknown, state: appendRecord(input.state, unknown) },
      retryability: "WAIT"
    });
  }

  if (!isTerminal(input.outcome.claimState)) {
    return fail("FAILED", {
      field: "claimState",
      classification: "NON_TERMINAL_OUTCOME",
      message: "TerminalOutcome@v1 MUST use a terminal claim state"
    });
  }

  const terminals = terminalsForObservation(input.state, input.outcome.sourceObservationId);
  if (terminals.some((terminal) => terminal.mutationPerformed === true) && input.outcome.mutationPerformed === true) {
    return fail("HOLD", {
      classification: "MUTATION_ATTEMPTS_EXCEEDED",
      message: "mutation attempts per observation <= 1"
    });
  }

  return ok({
    record: input.outcome,
    state: appendRecord(input.state, input.outcome)
  });
}

export function newObservationRequiredMeansImmediateRetry(_classification: string): boolean {
  return false;
}

export function canStartExecutableAttempt(input: {
  winningAttemptPhase?: WinningAttemptPhase;
  lastTerminal?: TerminalOutcomeV1;
  reconciliationProvesSafe?: boolean;
}): StructuredResult<void> {
  if (input.winningAttemptPhase !== undefined && (NON_TERMINAL_WINNER as readonly string[]).includes(input.winningAttemptPhase)) {
    return fail("HOLD", {
      classification: "CLAIM_REJECTED",
      retryability: "WAIT",
      message: "MUST NOT start a new executable attempt while the winning attempt is non-terminal"
    });
  }
  if (input.lastTerminal?.mutationPerformed === "UNKNOWN" || input.lastTerminal?.claimState === "TERMINAL_OUTCOME_UNKNOWN") {
    return fail("HOLD", {
      classification: "TERMINAL_OUTCOME_UNKNOWN",
      retryability: "WAIT",
      message: "TERMINAL_OUTCOME_UNKNOWN → HOLD → reconciliation required → no blind retry"
    });
  }
  if (input.lastTerminal?.claimState === "TERMINAL_NO_MUTATION") {
    return ok(undefined);
  }
  if (input.reconciliationProvesSafe === true) {
    return ok(undefined);
  }
  return fail("HOLD", {
    classification: "NEW_OBSERVATION_REQUIRED",
    retryability: "NEW_OBSERVATION_REQUIRED",
    message: "NEW_OBSERVATION_REQUIRED != immediate retry authorized"
  });
}
